spring:
  profiles: default

cache :
  url :
    csv : "http://localhost:8090/getCSV"
    update: "http://localhost:8090/update"

---
spring:
  profiles: develop

cache :
  url :
    csv : "https://sheethandler-dev.cfapps.io/getCSV"
    update: "https://sheethandler-dev.cfapps.io/update"

---
spring:
  profiles: production

cache :
  url :
    csv : "https://sheethandler-prod.cfapps.io/getCSV"
    update: "https://sheethandler-prod.cfapps.io/update"